//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.RepairLogs = new HashSet<RepairLog>();
            this.UsedParts = new HashSet<UsedPart>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<int> MasterID { get; set; }
        public int StatusID { get; set; }
        public string ProblemDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Device Device { get; set; }
        public virtual Master Master { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairLog> RepairLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedPart> UsedParts { get; set; }
    }
}
