//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepairServiceDBEntities : DbContext
    {
        private static RepairServiceDBEntities _context;
        public RepairServiceDBEntities()
            : base("name=RepairServiceDBEntities")
        {
        }
        public static RepairServiceDBEntities GetContext()
        {
            if (_context == null )
                _context = new RepairServiceDBEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<RepairLog> RepairLogs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SparePart> SpareParts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypicalFault> TypicalFaults { get; set; }
        public virtual DbSet<UsedPart> UsedParts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
