//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypicalFault
    {
        public int FaultID { get; set; }
        public string FaultName { get; set; }
        public string Description { get; set; }
        public string RecommendedSolution { get; set; }
    }
}
