//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedPart
    {
        public int UsedPartID { get; set; }
        public int OrderID { get; set; }
        public int PartID { get; set; }
        public int QuantityUsed { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SparePart SparePart { get; set; }
    }
}
